### PR TITLE
feat: changes to inertiajs packages for the imminent release of inertiajs v1

### PR DESCRIPTION
**Pull request by bobbypiper**
Updated package references to Inertiajs for the imminent release of V1.

https://next.inertiajs.com/upgrade-guide

Understandable if want to hold off on merging until V1 is out of beta.

### CODE REVIEW

**Comment by felipeva** [comment]
@bobbypiper Thank you!

Let's wait until v1 is out to merge this PR.

**Comment by bobbypiper** [comment]
@FelipeVa no problem, I expected as much - I made the change as I've an application already running with Inertia v1.

**Comment by felipeva** [comment]
@bobbypiper Is there a way you can update this PR, now that Inertia V1 is officially launched?

Thank you!

**Comment by felipeva** [comment]
All the inertia dependencies were upgrade to the latest version on #4

**Pull request closed without merging**
